# Generated by Django 3.2.4 on 2021-06-26 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='bar_code',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
