# Generated by Django 3.2.4 on 2022-01-22 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_clients', '0003_rename_client_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='purchase_counter',
            field=models.IntegerField(default=0),
        ),
    ]
