# Generated by Django 3.2.4 on 2022-01-23 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_clients', '0004_customer_purchase_counter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='purchase_counter',
        ),
    ]
