# Generated by Django 4.0.5 on 2022-06-09 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reference', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='emumerator',
            field=models.IntegerField(null=True),
        ),
    ]
