# Generated by Django 3.2.4 on 2022-06-09 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reference', '0002_remove_product_emumerator'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='emumerator',
            field=models.IntegerField(null=True),
        ),
    ]
