# Generated by Django 3.2.4 on 2021-06-26 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reference', '0002_alter_product_imei'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='cashback_percent',
            field=models.IntegerField(default=0),
        ),
    ]
