# Generated by Django 4.0.5 on 2022-06-09 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_reference', '0002_product_emumerator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='img',
        ),
    ]
