# Generated by Django 3.2.4 on 2022-06-09 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_reference', '0003_product_emumerator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='emumerator',
        ),
    ]
