# Generated by Django 3.2.4 on 2022-07-25 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reference', '0003_remove_product_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='sale_k',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=3),
        ),
    ]
