# Generated by Django 4.0.5 on 2022-06-09 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reference', '0003_remove_product_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='img',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
