# Generated by Django 3.2.4 on 2021-07-01 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reference', '0004_productcategory_bonus_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='sale_k',
            field=models.IntegerField(default=1),
        ),
    ]
