# Generated by Django 3.2.4 on 2021-07-01 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reference', '0005_shop_sale_k'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='bonus_percent',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=3),
        ),
    ]
