# Generated by Django 4.1.7 on 2023-09-13 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reference', '0005_alter_product_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teko_pay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
