# Generated by Django 3.2.4 on 2021-07-01 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reference', '0006_alter_productcategory_bonus_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='bonus_percent',
            field=models.IntegerField(default=0),
        ),
    ]
