# Generated by Django 4.1.7 on 2023-11-18 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_reference', '0007_shop_monobrand'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='monobrand',
            new_name='cash_register',
        ),
    ]
