# Generated by Django 3.2.4 on 2023-12-04 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reference', '0008_rename_monobrand_shop_cash_register'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='shift_status',
            field=models.BooleanField(default=False),
        ),
    ]
