# Generated by Django 3.2.4 on 2021-08-06 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_reference', '0009_documenttype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcategory',
            name='cashback_percent',
        ),
    ]
