# Generated by Django 3.2.4 on 2023-12-04 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reference', '0009_shop_shift_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='shift_status_updated',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
