# Generated by Django 3.2.4 on 2021-08-26 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_reference', '0010_remove_productcategory_cashback_percent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documenttype',
            options={'verbose_name': 'document'},
        ),
    ]
