# Generated by Django 4.1.7 on 2023-12-09 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reference', '0011_alter_shop_shift_status_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='subdealer',
            field=models.BooleanField(default=False),
        ),
    ]
