# Generated by Django 4.1.7 on 2023-12-09 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reference', '0012_shop_subdealer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subdealer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
