# Generated by Django 4.1.7 on 2023-12-09 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_reference', '0013_subdealer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subdealer',
        ),
    ]
