# Generated by Django 3.2.4 on 2021-10-11 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reference', '0014_voucher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
