# Generated by Django 3.2.4 on 2021-12-06 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reference', '0016_contributor'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='retail',
            field=models.BooleanField(default=True),
        ),
    ]
