# Generated by Django 3.2.4 on 2024-02-26 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reference', '0016_acquiringterminal'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='TID',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='commission',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=3),
        ),
        migrations.DeleteModel(
            name='AcquiringTerminal',
        ),
    ]
