# Generated by Django 3.2.4 on 2024-02-27 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reference', '0017_auto_20240227_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='commission',
            field=models.DecimalField(decimal_places=2, default=2.1, max_digits=3),
        ),
    ]
