# Generated by Django 3.2.4 on 2022-03-18 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_reference', '0017_shop_retail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documenttype',
            options={'verbose_name': 'documentType'},
        ),
    ]
