# Generated by Django 3.2.4 on 2022-05-03 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reference', '0018_alter_documenttype_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('retail_price', models.IntegerField(default=0, null=True)),
                ('bonus_percent', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
        ),
        migrations.AlterModelOptions(
            name='shop',
            options={'ordering': ('name',)},
        ),
    ]
