# Generated by Django 3.2.4 on 2024-04-07 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reference', '0020_auto_20240408_0012'),
    ]

    operations = [
        migrations.AddField(
            model_name='month',
            name='number_of_days',
            field=models.IntegerField(null=True),
        ),
    ]
