# Generated by Django 3.2.4 on 2024-04-14 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reference', '0021_month_number_of_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='offline',
            field=models.BooleanField(default=True),
        ),
    ]
