# Generated by Django 3.2.4 on 2024-04-15 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reference', '0022_shop_offline'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='MB',
            field=models.BooleanField(default=True),
        ),
    ]
