# Generated by Django 3.2.4 on 2024-05-25 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reference', '0023_shop_mb'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='bonus_percent_1',
            field=models.DecimalField(decimal_places=2, max_digits=3, null=True),
        ),
    ]
