# Generated by Django 3.2.4 on 2024-08-22 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reference', '0026_product_for_mp_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ozon_id',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
