# Generated by Django 3.2.4 on 2024-08-22 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reference', '0027_alter_product_ozon_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=160),
        ),
    ]
