# Generated by Django 3.2.4 on 2025-02-19 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_reference', '0035_sku'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sku',
            old_name='EAN',
            new_name='ean',
        ),
        migrations.AddField(
            model_name='sku',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_reference.productcategory'),
        ),
    ]
