# Generated by Django 3.2.4 on 2025-02-19 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reference', '0036_auto_20250219_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sku',
            name='ean',
            field=models.CharField(max_length=13, null=True),
        ),
    ]
