# Generated by Django 3.2.4 on 2025-02-19 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reference', '0037_alter_sku_ean'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sku',
            name='ean',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
