# Generated by Django 3.2.4 on 2025-02-20 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reference', '0041_auto_20250220_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ean',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
