# Generated by Django 3.2.4 on 2025-02-20 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reference', '0042_alter_product_ean'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ean',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
