# Generated by Django 3.2.4 on 2025-02-20 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reference', '0043_alter_product_ean'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='complex',
            field=models.BooleanField(default=True),
        ),
    ]
