# Generated by Django 3.2.4 on 2025-02-21 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reference', '0044_productcategory_complex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='emumerator',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_file',
            field=models.FileField(blank=True, null=True, upload_to='uploads'),
        ),
        migrations.AlterField(
            model_name='product',
            name='ozon_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
