# Generated by Django 3.2.4 on 2025-02-21 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reference', '0045_auto_20250221_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sku',
            name='emumerator',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sku',
            name='image_file_1',
            field=models.FileField(blank=True, null=True, upload_to='uploads'),
        ),
        migrations.AlterField(
            model_name='sku',
            name='image_file_2',
            field=models.FileField(blank=True, null=True, upload_to='uploads'),
        ),
        migrations.AlterField(
            model_name='sku',
            name='image_file_3',
            field=models.FileField(blank=True, null=True, upload_to='uploads'),
        ),
        migrations.AlterField(
            model_name='sku',
            name='ozon_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='sku',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='uploads'),
        ),
    ]
