# Generated by Django 3.2.4 on 2025-06-03 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reference', '0046_auto_20250221_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='TID',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
