# Generated by Django 3.2.4 on 2026-03-10 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reference', '0047_alter_shop_tid'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='address',
            field=models.CharField(blank=True, max_length=180, null=True),
        ),
    ]
