# Generated by Django 4.0.5 on 2022-07-12 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_reference', '0003_remove_product_status'),
        ('app_sims', '0002_simreturnrecord_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='simreturnrecord',
            name='rho_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_reference.documenttype'),
        ),
    ]
