# Generated by Django 4.0.5 on 2022-07-12 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_sims', '0003_simreturnrecord_rho_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='simreturnrecord',
            name='enumerator',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
