# Generated by Django 4.0.5 on 2022-07-12 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_sims', '0004_simreturnrecord_enumerator'),
    ]

    operations = [
        migrations.RenameField(
            model_name='simreturnrecord',
            old_name='rho_type',
            new_name='srr_type',
        ),
    ]
