# Generated by Django 4.1.7 on 2023-12-21 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_sims', '0007_simsupplierreturnrecord_simsigningoffrecord'),
    ]

    operations = [
        migrations.RenameField(
            model_name='simsigningoffrecord',
            old_name='sim_reg_type',
            new_name='doc_type',
        ),
        migrations.RenameField(
            model_name='simsupplierreturnrecord',
            old_name='sim_reg_type',
            new_name='doc_type',
        ),
    ]
