# Generated by Django 3.2.4 on 2026-08-18 09:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VMR_check',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('shop', models.CharField(max_length=50, null=True)),
                ('client_problem_resolution', models.BooleanField(default=False)),
                ('mnp_offer', models.BooleanField(default=False)),
                ('sim_offer', models.BooleanField(default=False)),
                ('mixx_offer', models.BooleanField(default=False)),
                ('phone_offer', models.BooleanField(default=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
