# Generated by Django 3.2.4 on 2026-08-18 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_vmr', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vmr_check',
            old_name='client_problem_resolution',
            new_name='client_problem_res',
        ),
    ]
