# Generated by Django 3.2.4 on 2026-08-18 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_vmr', '0002_rename_client_problem_resolution_vmr_check_client_problem_res'),
    ]

    operations = [
        migrations.AddField(
            model_name='vmr_check',
            name='rtc_offer',
            field=models.BooleanField(default=False),
        ),
    ]
