# Generated by Django 3.2.4 on 2026-08-19 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_vmr', '0003_vmr_check_rtc_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vmr_check',
            name='client_problem_res',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='vmr_check',
            name='phone_offer',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
