# Generated by Django 3.2.4 on 2024-04-07 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_kpi', '0002_auto_20240408_0219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kpimonthlyplan',
            name='month_reported',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='kpimonthlyplan',
            name='year_reported',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
