# Generated by Django 3.2.4 on 2024-04-07 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_kpi', '0003_auto_20240408_0239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kpimonthlyplan',
            name='shop',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
