# Generated by Django 3.2.4 on 2024-04-10 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_kpi', '0005_kpi_performance_identifier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kpi_performance',
            name='identifier',
        ),
    ]
