# Generated by Django 3.2.4 on 2024-04-10 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_reference', '0021_month_number_of_days'),
        ('app_kpi', '0007_auto_20240410_2353'),
    ]

    operations = [
        migrations.CreateModel(
            name='KPI_Forecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GI', models.IntegerField(default=0, null=True)),
                ('MNP', models.IntegerField(default=0, null=True)),
                ('HighBundle', models.IntegerField(default=0, null=True)),
                ('HomeInternet_T2', models.IntegerField(default=0, null=True)),
                ('HomeInternet_RT', models.IntegerField(default=0, null=True)),
                ('smartphones_sum', models.IntegerField(default=0, null=True)),
                ('RT_active_cam', models.IntegerField(default=0, null=True)),
                ('RT_equip_roubles', models.IntegerField(default=0, null=True)),
                ('wink_item', models.IntegerField(default=0, null=True)),
                ('wink_roubles', models.IntegerField(default=0, null=True)),
                ('upsale', models.IntegerField(default=0, null=True)),
                ('mixx', models.IntegerField(default=0, null=True)),
                ('golden_sim', models.IntegerField(default=0, null=True)),
                ('insurance_charge', models.IntegerField(default=0, null=True)),
                ('month_reported', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_reference.month')),
                ('shop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_reference.shop')),
                ('year_reported', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_reference.year')),
            ],
        ),
    ]
