# Generated by Django 3.2.4 on 2024-04-13 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_reference', '0021_month_number_of_days'),
        ('app_kpi', '0008_kpi_forecast'),
    ]

    operations = [
        migrations.CreateModel(
            name='GI_report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GI', models.IntegerField(default=0, null=True)),
                ('month_reported', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_reference.month')),
                ('shop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_reference.shop')),
                ('year_reported', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_reference.year')),
            ],
        ),
    ]
