# Generated by Django 3.2.4 on 2024-04-13 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0014_register_updated'),
        ('app_kpi', '0009_gi_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='gi_report',
            name='identifier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_product.identifier'),
        ),
    ]
