# Generated by Django 3.2.4 on 2024-04-14 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_kpi', '0010_gi_report_identifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='gi_report',
            name='GI_plan',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
