# Generated by Django 3.2.4 on 2024-04-27 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_kpi', '0013_focus_report'),
    ]

    operations = [
        migrations.RenameField(
            model_name='focus_report',
            old_name='GI',
            new_name='focus',
        ),
        migrations.RenameField(
            model_name='focus_report',
            old_name='GI_plan',
            new_name='focus_plan',
        ),
    ]
