# Generated by Django 3.2.4 on 2024-04-28 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0014_register_updated'),
        ('app_reference', '0023_shop_mb'),
        ('app_kpi', '0014_auto_20240427_1851'),
    ]

    operations = [
        migrations.CreateModel(
            name='HI_report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HI_plan', models.IntegerField(default=0, null=True)),
                ('HI', models.IntegerField(default=0, null=True)),
                ('date_before_current', models.IntegerField(default=0, null=True)),
                ('days_of_the_month', models.IntegerField(default=0, null=True)),
                ('identifier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_product.identifier')),
                ('month_reported', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_reference.month')),
                ('shop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_reference.shop')),
                ('year_reported', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_reference.year')),
            ],
        ),
        migrations.DeleteModel(
            name='KPI_Forecast',
        ),
    ]
