# Generated by Django 3.2.4 on 2024-04-28 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_kpi', '0015_auto_20240428_1529'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kpimonthlyplan',
            old_name='HomeInternet',
            new_name='HomeInternet_RT',
        ),
        migrations.AddField(
            model_name='kpimonthlyplan',
            name='HomeInternet_T2',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
