# Generated by Django 3.2.4 on 2022-06-27 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tutorial', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='thumbnail_file',
            field=models.FileField(null=True, upload_to='uploads'),
        ),
    ]
