# Generated by Django 3.2.4 on 2021-08-06 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cashback', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashback',
            name='size',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
