# Generated by Django 3.2.4 on 2021-08-06 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cashback', '0002_alter_cashback_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashback',
            name='size',
            field=models.IntegerField(default=0),
        ),
    ]
