# Generated by Django 3.2.4 on 2021-07-01 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_personnel', '0002_auto_20210701_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonusaccount',
            name='acces',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bonusaccount',
            name='esset',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bonusaccount',
            name='insurance',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bonusaccount',
            name='modems',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bonusaccount',
            name='phones',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bonusaccount',
            name='service',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bonusaccount',
            name='sim',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bonusaccount',
            name='smarts',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bonusaccount',
            name='wink',
            field=models.IntegerField(default=0),
        ),
    ]
