# Generated by Django 3.2.4 on 2021-07-01 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_personnel', '0003_auto_20210701_2243'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BonusAccount',
        ),
    ]
