# Generated by Django 3.2.4 on 2021-07-02 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_reference', '0008_alter_productcategory_bonus_percent'),
        ('app_personnel', '0005_bonusaccount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonusaccount',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app_reference.productcategory'),
        ),
    ]
