# Generated by Django 3.2.4 on 2021-07-02 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_personnel', '0006_alter_bonusaccount_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bonusaccount',
            name='bonus',
        ),
        migrations.RemoveField(
            model_name='bonusaccount',
            name='category',
        ),
        migrations.AddField(
            model_name='bonusaccount',
            name='acces',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bonusaccount',
            name='esset',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bonusaccount',
            name='insurance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bonusaccount',
            name='modems',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bonusaccount',
            name='phones',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bonusaccount',
            name='service',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bonusaccount',
            name='sims',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bonusaccount',
            name='smarts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bonusaccount',
            name='wink',
            field=models.IntegerField(default=0),
        ),
    ]
