# Generated by Django 3.2.4 on 2021-07-02 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_personnel', '0007_auto_20210702_0950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bonusaccount',
            name='smarts',
        ),
    ]
