# Generated by Django 3.2.4 on 2021-06-17 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='document',
        ),
        migrations.AddField(
            model_name='register',
            name='identifier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_product.identifier'),
        ),
    ]
