# Generated by Django 3.2.4 on 2022-08-02 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_reference', '0004_alter_shop_sale_k'),
        ('app_product', '0002_tradein'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradein',
            name='shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_reference.shop'),
        ),
    ]
