# Generated by Django 3.2.4 on 2021-06-07 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0002_remove_sale_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remainder',
            name='document',
        ),
    ]
