# Generated by Django 3.2.4 on 2021-06-17 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0002_auto_20210617_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
