# Generated by Django 3.2.4 on 2021-06-07 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0003_remove_remainder_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remainder',
            name='price',
        ),
    ]
