# Generated by Django 3.2.4 on 2022-09-21 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0003_tradein_shop'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tradein',
            old_name='name',
            new_name='model',
        ),
    ]
