# Generated by Django 3.2.4 on 2023-10-14 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0004_rename_name_tradein_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='av_price',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_product.avprice'),
        ),
    ]
