# Generated by Django 3.2.4 on 2021-06-24 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0004_alter_register_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transfer',
            name='date',
        ),
    ]
