# Generated by Django 3.2.4 on 2021-06-07 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_reference', '0001_initial'),
        ('app_product', '0004_remove_remainder_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('imei', models.CharField(max_length=250)),
                ('price', models.IntegerField(default=0)),
                ('quantity_plus', models.IntegerField(default=0)),
                ('quantity_minus', models.IntegerField(default=0)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app_product.document')),
                ('receiver_shop', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='receiver_shop', to='app_reference.shop')),
                ('sender_shop', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sender_shop', to='app_reference.shop')),
            ],
            options={
                'verbose_name': 'transfer',
                'verbose_name_plural': 'transfers',
            },
        ),
    ]
