# Generated by Django 3.2.4 on 2021-06-26 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_reference', '0002_alter_product_imei'),
        ('app_product', '0005_remove_transfer_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_reference.shop'),
        ),
    ]
