# Generated by Django 3.2.4 on 2021-06-07 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0005_transfer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transfer',
            old_name='quantity_minus',
            new_name='quantity',
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='quantity_plus',
        ),
    ]
