# Generated by Django 3.2.4 on 2024-03-20 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0005_register_av_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='reevaluation_price',
            field=models.IntegerField(null=True),
        ),
    ]
