# Generated by Django 3.2.4 on 2024-03-21 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_reference', '0018_alter_shop_commission'),
        ('app_product', '0006_register_reevaluation_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='shop_being_invetoried',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='shop_being_inventoried', to='app_reference.shop'),
        ),
    ]
