# Generated by Django 3.2.4 on 2021-07-01 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_reference', '0008_alter_productcategory_bonus_percent'),
        ('app_product', '0007_sale_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_reference.supplier'),
        ),
    ]
