# Generated by Django 3.2.4 on 2024-03-21 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0008_rename_shop_being_invetoried_document_shop_being_inventoried'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='shop_being_inventoried',
        ),
    ]
