# Generated by Django 3.2.4 on 2021-07-01 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0008_sale_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='sub_total',
            field=models.IntegerField(default=0),
        ),
    ]
