# Generated by Django 3.2.4 on 2021-07-01 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0009_document_sub_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='sub_total',
            new_name='sum',
        ),
    ]
