# Generated by Django 3.2.4 on 2021-07-01 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0010_rename_sub_total_document_sum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='sum',
            field=models.IntegerField(null=True),
        ),
    ]
