# Generated by Django 3.2.4 on 2024-03-21 22:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_reference', '0018_alter_shop_commission'),
        ('app_product', '0010_alter_register_reevaluation_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(null=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('imei', models.CharField(max_length=250, null=True)),
                ('name', models.CharField(max_length=250, null=True)),
                ('quantity', models.IntegerField(default=1)),
                ('real_quantity', models.IntegerField(null=True)),
                ('price', models.IntegerField(default=0)),
                ('reevaluation_price', models.IntegerField(default=0)),
                ('sub_total', models.BigIntegerField(default=0)),
                ('doc_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_reference.documenttype')),
                ('document', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_product.document')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_reference.product')),
                ('shop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_reference.shop')),
            ],
        ),
    ]
