# Generated by Django 3.2.4 on 2024-03-22 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0011_inventorylist'),
    ]

    operations = [
        migrations.AddField(
            model_name='remainderhistory',
            name='updated',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
