# Generated by Django 3.2.4 on 2021-07-01 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0012_document_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='datetime',
        ),
    ]
