# Generated by Django 3.2.4 on 2024-03-29 07:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0013_alter_remainderhistory_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='updated',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
