# Generated by Django 3.2.4 on 2021-07-01 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0014_delivery_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
