# Generated by Django 3.2.4 on 2021-07-01 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0015_sale_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='remainder',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='transfer',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
