# Generated by Django 3.2.4 on 2025-02-19 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_reference', '0038_alter_sku_ean'),
        ('app_product', '0015_auto_20240809_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='ean',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_reference.sku'),
        ),
    ]
