# Generated by Django 3.2.4 on 2021-07-01 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0016_auto_20210701_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='staff_bonus',
            field=models.IntegerField(default=0),
        ),
    ]
