# Generated by Django 3.2.4 on 2025-02-20 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0016_register_ean'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='ean',
            new_name='sku',
        ),
    ]
