# Generated by Django 3.2.4 on 2021-07-01 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_reference', '0008_alter_productcategory_bonus_percent'),
        ('app_product', '0017_sale_staff_bonus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='identifier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_product.identifier'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_reference.supplier'),
        ),
    ]
