# Generated by Django 3.2.4 on 2025-02-21 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_reference', '0044_productcategory_complex'),
        ('app_product', '0017_rename_ean_register_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='remainderhistory',
            name='sku',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_reference.sku'),
        ),
    ]
