# Generated by Django 3.2.4 on 2025-02-21 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0018_remainderhistory_sku'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remainderhistory',
            name='sku',
        ),
        migrations.AddField(
            model_name='remainderhistory',
            name='ean',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
