# Generated by Django 3.2.4 on 2021-07-04 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0018_auto_20210701_2334'),
    ]

    operations = [
        migrations.RenameField(
            model_name='remainder',
            old_name='quantity_remainder',
            new_name='current_remainder',
        ),
        migrations.AddField(
            model_name='remainder',
            name='document',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='remainder',
            name='incoming_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='remainder',
            name='outgoing_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='remainder',
            name='pre_remainder',
            field=models.IntegerField(default=0),
        ),
    ]
