# Generated by Django 3.2.4 on 2021-07-04 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_reference', '0008_alter_productcategory_bonus_percent'),
        ('app_product', '0019_auto_20210704_1215'),
    ]

    operations = [
        migrations.CreateModel(
            name='RemainderCurrent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('imei', models.CharField(max_length=250)),
                ('current_remainder', models.IntegerField(default=0)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app_reference.shop')),
            ],
        ),
    ]
