# Generated by Django 3.2.4 on 2025-03-06 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0019_auto_20250221_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='avprice',
            name='ean',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='avprice',
            name='imei',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
