# Generated by Django 3.2.4 on 2021-07-04 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_reference', '0008_alter_productcategory_bonus_percent'),
        ('app_product', '0020_remaindercurrent'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Remainder',
            new_name='RemainderHistory',
        ),
    ]
