# Generated by Django 3.2.4 on 2021-07-04 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0021_rename_remainder_remainderhistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='remainderhistory',
            options={},
        ),
    ]
