# Generated by Django 3.2.4 on 2025-05-23 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0021_remove_avprice_ean'),
    ]

    operations = [
        migrations.AddField(
            model_name='remaindercurrent',
            name='av_price',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='remaindercurrent',
            name='retail_price',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
