# Generated by Django 3.2.4 on 2025-05-29 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_reference', '0046_auto_20250221_1444'),
        ('app_product', '0022_auto_20250523_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='remaindercurrent',
            name='wholesale_price',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='remaindercurrent',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_reference.productcategory'),
        ),
    ]
