# Generated by Django 3.2.4 on 2021-07-04 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0022_alter_remainderhistory_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remainderhistory',
            name='av_price',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
