# Generated by Django 3.2.4 on 2025-05-29 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0023_auto_20250529_2327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remaindercurrent',
            name='wholesale_price',
        ),
    ]
