# Generated by Django 3.2.4 on 2021-07-04 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_reference', '0008_alter_productcategory_bonus_percent'),
        ('app_product', '0023_alter_remainderhistory_av_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remainderhistory',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_reference.productcategory'),
        ),
    ]
