# Generated by Django 3.2.4 on 2026-01-09 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0024_remove_remaindercurrent_wholesale_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remainderhistory',
            name='mp_RRP',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
