# Generated by Django 3.2.4 on 2026-10-08 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0025_alter_remainderhistory_mp_rrp'),
    ]

    operations = [
        migrations.AddField(
            model_name='remainderhistory',
            name='code_mark',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
