# Generated by Django 3.2.4 on 2021-07-04 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0027_delivery_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='sub_total',
            field=models.IntegerField(default=0),
        ),
    ]
