# Generated by Django 3.2.4 on 2021-07-04 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0028_delivery_sub_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='delivery', to='app_product.document'),
        ),
    ]
