# Generated by Django 3.2.4 on 2021-07-08 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0037_remaindercurrent_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remainderhistory',
            name='incoming_quantity',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='remainderhistory',
            name='outgoing_quantity',
            field=models.IntegerField(null=True),
        ),
    ]
