# Generated by Django 3.2.4 on 2021-07-10 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0038_auto_20210708_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='remainderhistory',
            name='update_check',
            field=models.BooleanField(default=False),
        ),
    ]
