# Generated by Django 3.2.4 on 2021-07-10 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0039_remainderhistory_update_check'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'verbose_name': 'self.title'},
        ),
    ]
