# Generated by Django 3.2.4 on 2021-07-10 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0040_alter_document_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={},
        ),
    ]
