# Generated by Django 3.2.4 on 2021-07-10 14:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0041_alter_document_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
