# Generated by Django 3.2.4 on 2021-07-10 14:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0042_document_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='created',
        ),
        migrations.RemoveField(
            model_name='document',
            name='created',
        ),
        migrations.RemoveField(
            model_name='remainderhistory',
            name='created',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='created',
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='created',
        ),
        migrations.AddField(
            model_name='delivery',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='remainderhistory',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='transfer',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
