# Generated by Django 3.2.4 on 2021-07-10 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0043_auto_20210710_1759'),
    ]

    operations = [
        migrations.RenameField(
            model_name='delivery',
            old_name='datetime',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='datetime',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='remainderhistory',
            old_name='datetime',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='sale',
            old_name='datetime',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='transfer',
            old_name='datetime',
            new_name='created',
        ),
    ]
