# Generated by Django 3.2.4 on 2021-07-11 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_reference', '0009_documenttype'),
        ('app_product', '0044_auto_20210710_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_reference.productcategory'),
        ),
    ]
