# Generated by Django 3.2.4 on 2021-07-13 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0045_alter_delivery_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='remaindercurrent',
            name='av_price',
            field=models.IntegerField(null=True),
        ),
    ]
