# Generated by Django 3.2.4 on 2021-07-13 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0046_remaindercurrent_av_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='remaindercurrent',
            name='total_av_price',
            field=models.IntegerField(null=True),
        ),
    ]
