# Generated by Django 3.2.4 on 2021-07-13 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0047_remaindercurrent_total_av_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='remainderhistory',
            name='wholesale_price',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
