# Generated by Django 3.2.4 on 2021-07-25 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0050_averagepricecurrent'),
    ]

    operations = [
        migrations.AddField(
            model_name='averagepricecurrent',
            name='remainder',
            field=models.IntegerField(null=True),
        ),
    ]
