# Generated by Django 3.2.4 on 2021-07-26 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0051_averagepricecurrent_remainder'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AveragePriceCurrent',
        ),
    ]
