# Generated by Django 3.2.4 on 2021-08-02 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0052_delete_averagepricecurrent'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('imei', models.CharField(max_length=250)),
                ('name', models.CharField(max_length=250, null=True)),
                ('current_remainder', models.IntegerField(default=0)),
                ('av_price', models.IntegerField(null=True)),
                ('sum', models.IntegerField(null=True)),
            ],
        ),
    ]
