# Generated by Django 3.2.4 on 2021-08-20 10:03

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_reference', '0010_remove_productcategory_cashback_percent'),
        ('app_product', '0059_return'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Return',
            new_name='Returning',
        ),
    ]
