# Generated by Django 3.2.4 on 2021-08-26 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_reference', '0011_alter_documenttype_options'),
        ('app_product', '0061_revaluation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_reference.shop'),
        ),
    ]
