# Generated by Django 3.2.4 on 2021-08-26 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0062_alter_delivery_shop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='identifier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_product.identifier'),
        ),
    ]
