# Generated by Django 3.2.4 on 2021-09-12 09:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0063_alter_delivery_identifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
