# Generated by Django 3.2.4 on 2021-09-13 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0066_alter_register_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='number',
            field=models.IntegerField(null=True),
        ),
    ]
