# Generated by Django 3.2.4 on 2021-09-21 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_reference', '0012_product_created'),
        ('app_product', '0067_register_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='remainderhistory',
            name='supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_reference.supplier'),
        ),
    ]
