# Generated by Django 3.2.4 on 2021-10-10 07:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_reference', '0012_product_created'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_product', '0071_remainderhistory_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashOff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('sub_total', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app_reference.shop')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
