# Generated by Django 3.2.4 on 2021-10-11 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_reference', '0015_auto_20211011_1008'),
        ('app_product', '0072_cashoff'),
    ]

    operations = [
        migrations.AddField(
            model_name='remaindercurrent',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_reference.productcategory'),
        ),
    ]
