# Generated by Django 3.2.4 on 2021-10-12 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0073_remaindercurrent_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='posted',
            field=models.BooleanField(default=False),
        ),
    ]
