# Generated by Django 3.2.4 on 2021-10-15 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0075_document_identifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='document',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_product.document'),
        ),
    ]
