# Generated by Django 3.2.4 on 2021-10-15 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_reference', '0015_auto_20211011_1008'),
        ('app_product', '0076_register_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_reference.supplier'),
        ),
    ]
