# Generated by Django 3.2.4 on 2021-10-17 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0078_register_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
