# Generated by Django 3.2.4 on 2021-11-25 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_reference', '0015_auto_20211011_1008'),
        ('app_product', '0092_auto_20211105_0117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_reference.product'),
        ),
    ]
