# Generated by Django 3.2.4 on 2021-12-05 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0097_register_receiver'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='receiver',
            new_name='cash_receiver',
        ),
    ]
