# Generated by Django 3.2.4 on 2021-12-09 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0099_register_current_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='imei',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='register',
            name='name',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
