# Generated by Django 3.2.4 on 2021-12-12 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_reference', '0017_shop_retail'),
        ('app_product', '0100_auto_20211210_0129'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='doc_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_reference.documenttype'),
        ),
    ]
