# Generated by Django 3.2.4 on 2021-12-12 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0101_register_doc_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='real_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
