# Generated by Django 3.2.4 on 2021-12-12 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0102_register_real_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='real_quantity',
            field=models.IntegerField(null=True),
        ),
    ]
