# Generated by Django 3.2.4 on 2021-12-19 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0104_document_base_doc'),
    ]

    operations = [
        migrations.AddField(
            model_name='remainderhistory',
            name='inventory_doc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='inventory', to='app_product.document'),
        ),
    ]
