# Generated by Django 3.2.4 on 2021-12-29 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_reference', '0017_shop_retail'),
        ('app_product', '0105_remainderhistory_inventory_doc'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_reference.shop'),
        ),
    ]
