# Generated by Django 3.2.4 on 2022-01-09 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0109_auto_20220109_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remainderhistory',
            name='inventory_doc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='inventory', to='app_product.document'),
        ),
    ]
