# Generated by Django 3.2.4 on 2022-01-09 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0110_alter_remainderhistory_inventory_doc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remaindercurrent',
            name='total_av_price',
        ),
    ]
