# Generated by Django 3.2.4 on 2022-01-09 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0111_remove_remaindercurrent_total_av_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remaindercurrent',
            name='av_price',
        ),
    ]
