# Generated by Django 3.2.4 on 2022-01-11 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0112_remove_remaindercurrent_av_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Delivery',
        ),
    ]
