# Generated by Django 3.2.4 on 2022-01-11 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0113_delete_delivery'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Recognition',
        ),
    ]
