# Generated by Django 3.2.4 on 2022-01-11 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0114_delete_recognition'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SignOff',
        ),
    ]
