# Generated by Django 3.2.4 on 2022-01-11 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0115_delete_signoff'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Returning',
        ),
    ]
