# Generated by Django 3.2.4 on 2022-01-23 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_clients', '0005_remove_customer_purchase_counter'),
        ('app_product', '0116_delete_returning'),
    ]

    operations = [
        migrations.AddField(
            model_name='remainderhistory',
            name='clinet_phone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_clients.customer'),
        ),
    ]
