# Generated by Django 3.2.4 on 2022-01-23 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0117_remainderhistory_clinet_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='remainderhistory',
            old_name='clinet_phone',
            new_name='client_phone',
        ),
    ]
