# Generated by Django 3.2.4 on 2022-01-28 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0118_rename_clinet_phone_remainderhistory_client_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='remainderhistory',
            name='number',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
