# Generated by Django 3.2.4 on 2022-02-02 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0120_remainderhistory_cash_back_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='remainderhistory',
            name='cash_back_awarded',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
