# Generated by Django 3.2.4 on 2022-02-02 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_reference', '0017_shop_retail'),
        ('app_product', '0121_remainderhistory_cash_back_awarded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remainderhistory',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_reference.supplier'),
        ),
    ]
