# Generated by Django 3.2.4 on 2022-02-02 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0123_register_cash_back'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='cash_back',
            new_name='cash_back_awarded',
        ),
        migrations.AddField(
            model_name='register',
            name='cash_back_paid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='register',
            name='client_phone',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
