# Generated by Django 3.2.4 on 2022-02-02 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_clients', '0005_remove_customer_purchase_counter'),
        ('app_product', '0124_auto_20220202_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='client_phone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_clients.customer'),
        ),
    ]
