# Generated by Django 3.2.4 on 2022-02-03 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0125_alter_register_client_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='cashback_off',
            field=models.IntegerField(default=0),
        ),
    ]
