# Generated by Django 3.2.4 on 2022-02-03 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0126_document_cashback_off'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='sum_minus_cashback',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
