# Generated by Django 3.2.4 on 2022-02-03 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_clients', '0005_remove_customer_purchase_counter'),
        ('app_product', '0127_document_sum_minus_cashback'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_clients.customer'),
        ),
    ]
