# Generated by Django 3.2.4 on 2022-02-03 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0129_remove_register_client_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='cash_back_paid',
        ),
    ]
