# Generated by Django 3.2.4 on 2022-02-03 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0130_remove_register_cash_back_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remainderhistory',
            name='cash_back_paid',
        ),
        migrations.RemoveField(
            model_name='remainderhistory',
            name='client_phone',
        ),
    ]
