# Generated by Django 3.2.4 on 2022-02-03 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0132_remove_remainderhistory_cash_back_awarded'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='cash_back_awarded',
        ),
        migrations.AddField(
            model_name='remainderhistory',
            name='cash_back_awarded',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
