# Generated by Django 3.2.4 on 2022-02-07 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0134_document_supplier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='shop',
        ),
        migrations.DeleteModel(
            name='Sale',
        ),
    ]
