# Generated by Django 3.2.4 on 2022-02-07 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_reference', '0017_shop_retail'),
        ('app_product', '0135_auto_20220207_1554'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='shop_receiver',
        ),
        migrations.RemoveField(
            model_name='register',
            name='shop_sender',
        ),
        migrations.AddField(
            model_name='document',
            name='shop_receiver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='shop_receiver', to='app_reference.shop'),
        ),
        migrations.AddField(
            model_name='document',
            name='shop_sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='shop_sender', to='app_reference.shop'),
        ),
    ]
