# Generated by Django 3.2.4 on 2022-02-19 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0136_auto_20220207_1706'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transfer',
        ),
    ]
