# Generated by Django 3.2.4 on 2022-02-20 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0137_delete_transfer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remainderhistory',
            name='current_remainder',
            field=models.BigIntegerField(default=0),
        ),
    ]
