# Generated by Django 3.2.4 on 2022-02-20 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0138_alter_remainderhistory_current_remainder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='sub_total',
            field=models.BigIntegerField(default=0),
        ),
    ]
