# Generated by Django 3.2.4 on 2022-02-20 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_reference', '0017_shop_retail'),
        ('app_product', '0139_alter_register_sub_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remainderhistory',
            name='product_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_reference.product'),
        ),
    ]
