# Generated by Django 3.2.4 on 2022-02-22 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0140_alter_remainderhistory_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remainderhistory',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
