# Generated by Django 3.2.4 on 2022-02-22 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0142_auto_20220222_0309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remainderhistory',
            name='updated',
        ),
    ]
