# Generated by Django 3.2.4 on 2022-03-18 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0143_remove_remainderhistory_updated'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Revaluation',
        ),
    ]
