# Generated by Django 3.2.4 on 2021-06-26 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0006_register_shop'),
        ('app_cash', '0002_auto_20210626_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='cash',
            name='document',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_product.document'),
        ),
    ]
