# Generated by Django 3.2.4 on 2021-06-26 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_reference', '0003_productcategory_cashback_percent'),
        ('app_cash', '0004_cashremainder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashremainder',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_reference.shop'),
        ),
    ]
