# Generated by Django 3.2.4 on 2021-07-03 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_cash', '0005_alter_cashremainder_shop'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cash',
            old_name='cash_remainder',
            new_name='current_remainder',
        ),
    ]
