# Generated by Django 3.2.4 on 2021-07-03 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cash', '0006_rename_cash_remainder_cash_current_remainder'),
    ]

    operations = [
        migrations.AddField(
            model_name='cash',
            name='pre_remainder',
            field=models.IntegerField(default=0),
        ),
    ]
