# Generated by Django 3.2.4 on 2021-08-04 13:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_cash', '0007_cash_pre_remainder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cash',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
