# Generated by Django 3.2.4 on 2021-08-04 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_cash', '0008_alter_cash_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='credit',
            old_name='credit_remainder',
            new_name='sum',
        ),
    ]
