# Generated by Django 3.2.4 on 2021-08-04 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_cash', '0010_auto_20210804_2110'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='credit_remainder',
            new_name='sum',
        ),
    ]
