# Generated by Django 3.2.4 on 2021-10-10 07:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_cash', '0011_rename_credit_remainder_card_sum'),
    ]

    operations = [
        migrations.AddField(
            model_name='cash',
            name='cash_receiver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cash_receiver', to=settings.AUTH_USER_MODEL),
        ),
    ]
