# Generated by Django 3.2.4 on 2021-10-10 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_reference', '0013_expense'),
        ('app_cash', '0012_cash_cash_receiver'),
    ]

    operations = [
        migrations.AddField(
            model_name='cash',
            name='reason',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_reference.expense'),
        ),
    ]
