# Generated by Django 3.2.4 on 2021-10-11 07:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_cash', '0013_cash_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='cash',
            name='contributor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='contributor', to=settings.AUTH_USER_MODEL),
        ),
    ]
