# Generated by Django 3.2.4 on 2021-10-11 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_cash', '0014_cash_contributor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cash',
            old_name='contributor',
            new_name='cash_contributor',
        ),
    ]
