# Generated by Django 3.2.4 on 2021-10-11 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_reference', '0015_auto_20211011_1008'),
        ('app_cash', '0015_rename_contributor_cash_cash_contributor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cash',
            old_name='reason',
            new_name='cash_off_reason',
        ),
        migrations.AddField(
            model_name='cash',
            name='cash_in_reason',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_reference.voucher'),
        ),
    ]
