# Generated by Django 3.2.4 on 2021-10-11 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_reference', '0015_auto_20211011_1008'),
        ('app_cash', '0016_auto_20211011_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='cash',
            name='rho_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_reference.documenttype'),
        ),
    ]
