# Generated by Django 3.2.4 on 2021-11-25 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cash', '0019_contributor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributor',
            name='name',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
