# Generated by Django 3.2.4 on 2021-11-26 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_reference', '0016_contributor'),
        ('app_cash', '0021_delete_contributor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cash',
            name='cash_contributor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='contributor', to='app_reference.contributor'),
        ),
    ]
