# Generated by Django 3.2.4 on 2022-02-20 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cash', '0024_paymentregister'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='credit',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
