# Generated by Django 3.2.4 on 2022-06-02 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salereport',
            name='category',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
