# Generated by Django 3.2.4 on 2022-06-21 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailysalerep',
            name='cashback',
            field=models.IntegerField(null=True),
        ),
    ]
