# Generated by Django 3.2.4 on 2021-07-01 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_reference', '0008_alter_productcategory_bonus_percent'),
        ('app_reports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('imei', models.CharField(max_length=50, unique=True)),
                ('quantity', models.IntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app_reference.productcategory')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app_reference.supplier')),
            ],
        ),
        migrations.DeleteModel(
            name='Product_history',
        ),
    ]
