# Generated by Django 3.2.4 on 2022-07-12 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reports', '0003_sim_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='salereport',
            name='imei',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
