# Generated by Django 3.2.4 on 2021-07-01 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reports', '0003_producthistory_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='producthistory',
            name='shop',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
