# Generated by Django 4.0.5 on 2022-07-12 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reports', '0004_salereport_imei'),
    ]

    operations = [
        migrations.AddField(
            model_name='sim_report',
            name='created',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sim_report',
            name='shop',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sim_report',
            name='user',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
