# Generated by Django 3.2.4 on 2021-07-01 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_reference', '0008_alter_productcategory_bonus_percent'),
        ('app_reports', '0004_producthistory_shop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producthistory',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_reference.productcategory'),
        ),
        migrations.AlterField(
            model_name='producthistory',
            name='shop',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='producthistory',
            name='supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_reference.supplier'),
        ),
    ]
