# Generated by Django 4.0.5 on 2022-07-12 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_reports', '0005_sim_report_created_sim_report_shop_sim_report_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sim_report',
            old_name='created',
            new_name='date',
        ),
    ]
