# Generated by Django 4.0.5 on 2022-07-12 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reports', '0006_rename_created_sim_report_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='sim_report',
            name='document',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
