# Generated by Django 3.2.4 on 2021-07-01 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reports', '0007_auto_20210701_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='producthistory',
            name='document_id',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
