# Generated by Django 4.0.5 on 2022-07-12 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reports', '0007_sim_report_document'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sim_report',
            old_name='status',
            new_name='doc_type',
        ),
        migrations.AddField(
            model_name='sim_report',
            name='return_mark',
            field=models.BooleanField(default=False),
        ),
    ]
