# Generated by Django 3.2.4 on 2021-10-02 12:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_reports', '0008_producthistory_document_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportTemp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, null=True)),
            ],
        ),
    ]
