# Generated by Django 4.0.5 on 2022-07-12 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reports', '0008_rename_status_sim_report_doc_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sim_report',
            name='return_mark',
            field=models.CharField(default='РФА не сдана', max_length=50),
        ),
    ]
