# Generated by Django 3.2.4 on 2021-10-02 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reports', '0009_reporttemp'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporttemp',
            name='end_remainder',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='reporttemp',
            name='imei',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='reporttemp',
            name='initial_remainder',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='reporttemp',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='reporttemp',
            name='quantity_in',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='reporttemp',
            name='quantity_out',
            field=models.IntegerField(null=True),
        ),
    ]
