# Generated by Django 3.2.4 on 2022-07-25 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_reports', '0010_rename_doc_type_sim_report_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlybonus',
            name='report_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_reports.reporttempid'),
        ),
    ]
