# Generated by Django 3.2.4 on 2021-12-08 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reports', '0011_auto_20211002_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporttemp',
            name='existance_check',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='reporttempid',
            name='existance_check',
            field=models.BooleanField(default=True),
        ),
    ]
