# Generated by Django 3.2.4 on 2022-07-25 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reports', '0011_monthlybonus_report_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlybonus',
            name='modems',
            field=models.IntegerField(null=True),
        ),
    ]
