# Generated by Django 3.2.4 on 2022-07-25 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reports', '0012_monthlybonus_modems'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monthlybonus',
            old_name='iphone',
            new_name='gadjets',
        ),
        migrations.AddField(
            model_name='monthlybonus',
            name='iphones',
            field=models.IntegerField(null=True),
        ),
    ]
