# Generated by Django 3.2.4 on 2021-12-29 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_reference', '0017_shop_retail'),
        ('app_reports', '0013_dailsaletemp'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DailSaleTemp',
            new_name='DailySaleTemp',
        ),
    ]
