# Generated by Django 3.2.4 on 2022-07-25 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_reports', '0013_auto_20220725_1017'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monthlybonus',
            old_name='smarphones',
            new_name='smartphones',
        ),
    ]
