# Generated by Django 3.2.4 on 2021-12-29 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_reports', '0014_rename_dailsaletemp_dailysaletemp'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailysaletemp',
            name='report_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_reports.reporttempid'),
        ),
    ]
