# Generated by Django 3.2.4 on 2022-07-25 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_reports', '0014_rename_smarphones_monthlybonus_smartphones'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monthlybonus',
            old_name='gadjets',
            new_name='gadgets',
        ),
    ]
