# Generated by Django 3.2.4 on 2021-12-30 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_reports', '0015_dailysaletemp_report_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DailySaleTemp',
        ),
    ]
