# Generated by Django 3.2.4 on 2022-07-25 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_reports', '0016_monthlybonus_bulk_tarif'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monthlybonus',
            old_name='bulk_tarif',
            new_name='bulk_tariffs',
        ),
    ]
