# Generated by Django 3.2.4 on 2022-07-25 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_reports', '0017_rename_bulk_tarif_monthlybonus_bulk_tariffs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monthlybonus',
            old_name='bulk_tariffs',
            new_name='bulk_sims',
        ),
    ]
