# Generated by Django 3.2.4 on 2022-09-21 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_reports', '0018_rename_bulk_tariffs_monthlybonus_bulk_sims'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=50, null=True)),
                ('shop', models.CharField(max_length=50, null=True)),
                ('created', models.CharField(max_length=50, null=True)),
                ('user', models.CharField(max_length=50, null=True)),
                ('cashback_awarded', models.CharField(max_length=50, null=True)),
                ('cashaback_off', models.CharField(max_length=50, null=True)),
                ('cashaback_remaining', models.CharField(max_length=50, null=True)),
                ('document', models.CharField(max_length=50, null=True)),
                ('count', models.IntegerField()),
                ('report_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_reports.reporttempid')),
            ],
        ),
    ]
