# Generated by Django 3.2.4 on 2021-12-30 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_reports', '0018_dailysalerep_iphone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailysalerep',
            old_name='Iphone',
            new_name='iphone',
        ),
    ]
