# Generated by Django 3.2.4 on 2022-01-01 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reports', '0019_rename_iphone_dailysalerep_iphone'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailysalerep',
            name='final_balance',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='dailysalerep',
            name='opening_balance',
            field=models.IntegerField(null=True),
        ),
    ]
