# Generated by Django 3.2.4 on 2022-09-21 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_reports', '0020_alter_clientreport_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientreport',
            old_name='cashaback_off',
            new_name='cashback_off',
        ),
        migrations.RenameField(
            model_name='clientreport',
            old_name='cashaback_remaining',
            new_name='cashback_remaining',
        ),
    ]
