# Generated by Django 3.2.4 on 2022-01-06 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_reports', '0024_monthlybonus_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monthlybonus',
            name='final_balance',
        ),
    ]
