# Generated by Django 4.1.7 on 2023-12-18 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reports', '0024_auto_20230715_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='sim_report',
            name='WD_status',
            field=models.BooleanField(default=False),
        ),
    ]
