# Generated by Django 4.1.7 on 2023-12-18 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reports', '0025_sim_report_wd_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sim_report',
            name='WD_status',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
