# Generated by Django 3.2.4 on 2022-01-06 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reports', '0025_remove_monthlybonus_final_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monthlybonus',
            name='user',
        ),
        migrations.AddField(
            model_name='monthlybonus',
            name='shop',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
