# Generated by Django 3.2.4 on 2022-01-06 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_reports', '0026_auto_20220107_0227'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monthlybonus',
            old_name='shop',
            new_name='user_name',
        ),
    ]
