# Generated by Django 3.2.4 on 2022-02-02 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_reference', '0017_shop_retail'),
        ('app_reports', '0027_rename_shop_monthlybonus_user_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleRegort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('av_sum', models.IntegerField(default=0)),
                ('quantity', models.IntegerField(default=0)),
                ('retail_sum', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app_reference.product')),
            ],
        ),
    ]
