# Generated by Django 3.2.4 on 2024-02-25 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reports', '0027_monthlybonus_cashback'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlybonus',
            name='number_of_work_days',
            field=models.IntegerField(null=True),
        ),
    ]
