# Generated by Django 3.2.4 on 2022-02-02 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_reference', '0017_shop_retail'),
        ('app_reports', '0028_saleregort'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SaleRegort',
            new_name='SaleReport',
        ),
    ]
