# Generated by Django 3.2.4 on 2022-02-02 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_reports', '0029_rename_saleregort_salereport'),
    ]

    operations = [
        migrations.AddField(
            model_name='salereport',
            name='report_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_reports.reporttempid'),
        ),
    ]
