# Generated by Django 3.2.4 on 2022-02-02 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reports', '0030_salereport_report_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salereport',
            name='product',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
