# Generated by Django 3.2.4 on 2024-02-26 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reports', '0031_rename_acquiringdreport_acquiringreport'),
    ]

    operations = [
        migrations.RenameField(
            model_name='acquiringreport',
            old_name='sum',
            new_name='sum_bank',
        ),
        migrations.AddField(
            model_name='acquiringreport',
            name='sum_retail',
            field=models.IntegerField(default=0),
        ),
    ]
