# Generated by Django 3.2.4 on 2022-02-19 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reports', '0031_alter_salereport_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='salereport',
            name='margin',
            field=models.IntegerField(default=0),
        ),
    ]
