# Generated by Django 3.2.4 on 2024-02-27 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reports', '0032_auto_20240227_0033'),
    ]

    operations = [
        migrations.AddField(
            model_name='acquiringreport',
            name='shop',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
