# Generated by Django 3.2.4 on 2022-02-19 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_reports', '0032_salereport_margin'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailysalerep',
            name='report_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_reports.reporttempid'),
        ),
    ]
