# Generated by Django 3.2.4 on 2022-02-19 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_reference', '0017_shop_retail'),
        ('app_reports', '0033_dailysalerep_report_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailysalerep',
            name='accessories',
        ),
        migrations.RemoveField(
            model_name='dailysalerep',
            name='card',
        ),
        migrations.RemoveField(
            model_name='dailysalerep',
            name='cash_move',
        ),
        migrations.RemoveField(
            model_name='dailysalerep',
            name='credit',
        ),
        migrations.RemoveField(
            model_name='dailysalerep',
            name='expenses',
        ),
        migrations.RemoveField(
            model_name='dailysalerep',
            name='final_balance',
        ),
        migrations.RemoveField(
            model_name='dailysalerep',
            name='insuranсе',
        ),
        migrations.RemoveField(
            model_name='dailysalerep',
            name='iphone',
        ),
        migrations.RemoveField(
            model_name='dailysalerep',
            name='opening_balance',
        ),
        migrations.RemoveField(
            model_name='dailysalerep',
            name='phones',
        ),
        migrations.RemoveField(
            model_name='dailysalerep',
            name='return_sum',
        ),
        migrations.RemoveField(
            model_name='dailysalerep',
            name='salary',
        ),
        migrations.RemoveField(
            model_name='dailysalerep',
            name='services',
        ),
        migrations.RemoveField(
            model_name='dailysalerep',
            name='sim_cards',
        ),
        migrations.RemoveField(
            model_name='dailysalerep',
            name='smarphones',
        ),
        migrations.RemoveField(
            model_name='dailysalerep',
            name='sub_total',
        ),
        migrations.RemoveField(
            model_name='dailysalerep',
            name='wink',
        ),
        migrations.AddField(
            model_name='dailysalerep',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_reference.productcategory'),
        ),
        migrations.AddField(
            model_name='dailysalerep',
            name='sum',
            field=models.IntegerField(default=0),
        ),
    ]
