# Generated by Django 3.2.4 on 2022-02-20 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reports', '0034_auto_20220220_0225'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailysalerep',
            name='accessories',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='dailysalerep',
            name='card',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='dailysalerep',
            name='cash_move',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='dailysalerep',
            name='credit',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='dailysalerep',
            name='expenses',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='dailysalerep',
            name='final_balance',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='dailysalerep',
            name='insuranсе',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='dailysalerep',
            name='iphone',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='dailysalerep',
            name='opening_balance',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='dailysalerep',
            name='phones',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='dailysalerep',
            name='return_sum',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='dailysalerep',
            name='salary',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='dailysalerep',
            name='services',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='dailysalerep',
            name='sim_cards',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='dailysalerep',
            name='smarphones',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='dailysalerep',
            name='sub_total',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='dailysalerep',
            name='wink',
            field=models.IntegerField(null=True),
        ),
    ]
