# Generated by Django 3.2.4 on 2024-02-28 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reports', '0034_deliveryreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryreport',
            name='supplier',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
