# Generated by Django 3.2.4 on 2022-02-20 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reports', '0036_dailysalerep_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailysalerep',
            name='created',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
