# Generated by Django 3.2.4 on 2022-02-20 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_reports', '0038_dailysalerep_pay_cards'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailysalerep',
            old_name='smarphones',
            new_name='smartphones',
        ),
    ]
