# Generated by Django 3.2.4 on 2024-04-09 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reports', '0038_alter_salaryreport_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailysalerep',
            name='RT_equipment',
            field=models.IntegerField(null=True),
        ),
    ]
