# Generated by Django 3.2.4 on 2022-02-20 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_reports', '0039_rename_smarphones_dailysalerep_smartphones'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailysalerep',
            name='shop',
        ),
    ]
