# Generated by Django 3.2.4 on 2022-02-20 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_reference', '0017_shop_retail'),
        ('app_reports', '0040_remove_dailysalerep_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailysalerep',
            name='shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_reference.shop'),
        ),
    ]
