# Generated by Django 3.2.4 on 2024-04-28 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reports', '0040_monthlybonus_rt_equipment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientHistoryReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=50, null=True)),
                ('document', models.CharField(max_length=50, null=True)),
                ('number_of_docs', models.IntegerField(null=True)),
                ('sum', models.IntegerField(null=True)),
                ('cashback_awarded', models.CharField(max_length=50, null=True)),
                ('cashback_off', models.CharField(max_length=50, null=True)),
                ('cashback_remaining', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
