# Generated by Django 3.2.4 on 2024-04-28 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reports', '0041_clienthistoryreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='clienthistoryreport',
            name='user',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
