# Generated by Django 3.2.4 on 2022-02-20 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reports', '0041_dailysalerep_shop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailysalerep',
            name='shop',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
