# Generated by Django 3.2.4 on 2024-04-30 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_reports', '0042_clienthistoryreport_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clienthistoryreport',
            name='document',
        ),
        migrations.AddField(
            model_name='clienthistoryreport',
            name='report_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_reports.reporttempid'),
        ),
    ]
