# Generated by Django 3.2.4 on 2022-02-20 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reports', '0042_alter_dailysalerep_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailysalerep',
            name='net_sales',
            field=models.IntegerField(null=True),
        ),
    ]
