# Generated by Django 3.2.4 on 2022-02-20 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_reports', '0043_dailysalerep_net_sales'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailysalerep',
            name='sub_total',
        ),
    ]
