# Generated by Django 3.2.4 on 2022-02-20 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_reports', '0045_remove_dailysalerep_sum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailysalerep',
            name='category',
        ),
    ]
