# Generated by Django 3.2.4 on 2025-07-07 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reports', '0046_alter_salereport_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailysalerep',
            name='protective_films',
            field=models.IntegerField(null=True),
        ),
    ]
