# Generated by Django 3.2.4 on 2022-02-20 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_reports', '0046_remove_dailysalerep_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayCardReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop', models.CharField(max_length=50, null=True)),
                ('product', models.CharField(max_length=50, null=True)),
                ('pre_remainder', models.IntegerField(default=0)),
                ('incoming_quantity', models.IntegerField(default=0)),
                ('outgoing_quantity', models.IntegerField(default=0)),
                ('current_remainder', models.IntegerField(default=0)),
                ('report_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_reports.reporttempid')),
            ],
        ),
    ]
