# Generated by Django 3.2.4 on 2025-07-26 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reports', '0047_dailysalerep_protective_films'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlybonus',
            name='protective_films',
            field=models.IntegerField(null=True),
        ),
    ]
