# Generated by Django 3.2.4 on 2022-02-20 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reports', '0047_paycardreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='paycardreport',
            name='created',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
