# Generated by Django 3.2.4 on 2022-03-04 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reports', '0048_paycardreport_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporttemp',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
