# Generated by Django 3.2.4 on 2026-01-07 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reports', '0049_dailyactivation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailyactivation',
            old_name='price',
            new_name='report_price',
        ),
        migrations.AddField(
            model_name='dailyactivation',
            name='shop_price',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
