# Generated by Django 3.2.4 on 2022-05-03 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reports', '0049_reporttemp_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailysalerep',
            name='gadgets',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='dailysalerep',
            name='modems',
            field=models.IntegerField(null=True),
        ),
    ]
