# Generated by Django 3.2.4 on 2026-01-07 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reports', '0050_auto_20260107_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyactivation',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
