# Generated by Django 3.2.4 on 2026-01-07 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reports', '0051_dailyactivation_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyactivation',
            name='activation_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
