# Generated by Django 3.2.4 on 2026-01-07 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_reference', '0047_alter_shop_tid'),
        ('app_reports', '0052_dailyactivation_activation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyactivation',
            name='rho_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_reference.documenttype'),
        ),
    ]
