# Generated by Django 3.2.4 on 2026-01-07 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reports', '0053_dailyactivation_rho_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyactivation',
            name='activation_date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
