# Generated by Django 3.2.4 on 2026-01-07 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reports', '0054_alter_dailyactivation_activation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyactivation',
            name='tarif_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
