# Generated by Django 3.2.4 on 2026-01-07 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reports', '0055_dailyactivation_tarif_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyactivation',
            name='rho_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
