# Generated by Django 3.2.4 on 2026-01-08 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reports', '0056_alter_dailyactivation_rho_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyactivation',
            name='activation_location',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
