# Generated by Django 3.2.4 on 2026-03-04 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reports', '0057_dailyactivation_activation_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporttemp',
            name='name',
            field=models.CharField(max_length=160, null=True),
        ),
    ]
