# Generated by Django 3.2.4 on 2026-08-24 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reports', '0058_alter_reporttemp_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlybonus',
            name='audit',
            field=models.IntegerField(null=True),
        ),
    ]
