# Generated by Django 3.2.4 on 2026-10-01 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_reports', '0059_monthlybonus_audit'),
    ]

    operations = [
        migrations.CreateModel(
            name='RemainderOutputReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop', models.CharField(blank=True, max_length=50, null=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('imei', models.CharField(blank=True, max_length=50, null=True)),
                ('retail_price', models.IntegerField(null=True)),
                ('report_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_reports.reporttempid')),
            ],
        ),
    ]
