# Generated by Django 3.2.4 on 2026-10-01 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reports', '0060_remainderoutputreport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remainderoutputreport',
            name='shop',
        ),
        migrations.AddField(
            model_name='remainderoutputreport',
            name='current_remainder',
            field=models.IntegerField(null=True),
        ),
    ]
