# Generated by Django 3.2.4 on 2026-10-01 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0025_alter_remainderhistory_mp_rrp'),
        ('app_reports', '0061_auto_20261001_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remainderoutputreport',
            name='report_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_product.identifier'),
        ),
    ]
