# Generated by Django 3.2.4 on 2026-10-01 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reports', '0062_alter_remainderoutputreport_report_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='remainderoutputreport',
            name='number',
            field=models.IntegerField(null=True),
        ),
    ]
